version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
    environment:
      ES_JAVA_OPTS: "-Xmx516m -Xms516m"
      discovery.type: single-node    
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "indAdmin@123"
    ports:
      - '9200:9200' 
      - '9300:9300'
    networks:
      - elk
    env_file:
      - security.env 

  logstash:
    image: logstash:8.11.0
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx516m -Xms516m"    
    networks:
      - elk

  kibana:
    image: kibana:8.11.0
    container_name: kibana
    restart: always
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml       
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://dev.indusspay.com:9200 
      - ELASTICSEARCH_HOSTS=http://dev.indusspay.com:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=indAdmin@123
    depends_on:
      - elasticsearch  
    networks:
      - elk
volumes:
  elastic_data: {}

networks:
  elk: {}
